adb.exe
adb.exe wait-for-device
adb.exe remount
adb.exe shell busybox mount -o rw,remount /system
adb.exe shell rm /system/app/AdobeReader.apk
adb.exe shell rm /system/app/ba-syncservice-app-signed.apk
adb.exe shell rm /system/app/BackupRestoreConfirmation.apk
adb.exe shell rm /system/app/Blockbuster.apk
adb.exe shell rm /system/app/BlueSky.apk
adb.exe shell rm /system/app/BooksPhone.apk
adb.exe shell rm /system/app/Burgundy.apk
adb.exe shell rm /system/app/ChromeBookmarksSyncAdapter.apk
adb.exe shell rm /system/app/com.htc.FriendStream3DWidget.apk
adb.exe shell rm /system/app/com.htc.htcmsgwidgets3d.apk
adb.exe shell rm /system/app/com.htc.idlescreen_SN.apk
adb.exe shell rm /system/app/com.htc.MusicWidget.apk
adb.exe shell rm /system/app/com.htc.Sync3DWidget.apk
adb.exe shell rm /system/app/com.htc.Task3DWidget.apk
adb.exe shell rm /system/app/com.htc.TrendsWidget.apk
adb.exe shell rm /system/app/com.htc.Twitter3DWidget.apk
adb.exe shell rm /system/app/com.mobitv.client.nfl2010.apk
adb.exe shell rm /system/app/DFPI.apk
adb.exe shell rm /system/app/DMPortRead.apk
adb.exe shell rm /system/app/DockMode.apk
adb.exe shell rm /system/app/DrmProvider.apk
adb.exe shell rm /system/app/EPST.apk
adb.exe shell rm /system/app/FieldTrial.apk
adb.exe shell rm /system/app/FlashLitePlugin.apk
adb.exe shell rm /system/app/Flickr.apk
adb.exe shell rm /system/app/FriendStream.apk
adb.exe shell rm /system/app/fusion.apk
adb.exe shell rm /system/app/FusionStockWidget.apk
adb.exe shell rm /system/app/GSD.apk
adb.exe shell rm /system/app/HomePersonalize.apk
adb.exe shell rm /system/app/HTC_Diopen.apk
adb.exe shell rm /system/app/HTC_IME.apk
adb.exe shell rm /system/app/htc_vmm_hux.apk
adb.exe shell rm /system/app/HtcAutoRotateWidget.apk
adb.exe shell rm /system/app/HtcBackgroundDataWidget.apk
adb.exe shell rm /system/app/htcbookmarkwidget3d.apk
adb.exe shell rm /system/app/HtcCalculatorWidget.apk
adb.exe shell rm /system/app/htccalendarwidgets3d.apk
adb.exe shell rm /system/app/HtcCarPanel.apk
adb.exe shell rm /system/app/HtcCdmaMccProvider.apk
adb.exe shell rm /system/app/HtcClock3DWidget.apk
adb.exe shell rm /system/app/HtcCompressViewer.apk
adb.exe shell rm /system/app/HtcConnectedMedia.apk
adb.exe shell rm /system/app/htccontactwidgets3D.apk
adb.exe shell rm /system/app/HtcCOTAClient.apk
adb.exe shell rm /system/app/HtcDataRoamingWidget.apk
adb.exe shell rm /system/app/HtcDataStripWidget.apk
adb.exe shell rm /system/app/HtcDLNAMiddleLayer.apk
adb.exe shell rm /system/app/HtcDm.apk
adb.exe shell rm /system/app/HtcDMC.apk
adb.exe shell rm /system/app/HtcDmSettingsPlugin.apk
adb.exe shell rm /system/app/HtcFacebook.apk
adb.exe shell rm /system/app/HtcFacebookChat.apk
adb.exe shell rm /system/app/HtcFacebookChatWidget.apk
adb.exe shell rm /system/app/HtcFeedback.apk
adb.exe shell rm /system/app/HtcFootprints.apk
adb.exe shell rm /system/app/HtcFootprintsWidget3d.apk
adb.exe shell rm /system/app/HtcGreader.apk
adb.exe shell rm /system/app/HtcGreaderWidget.apk
adb.exe shell rm /system/app/HtcImageWallpaper.apk
adb.exe shell rm /system/app/HTCLivewallpaperStreak.apk
adb.exe shell rm /system/app/HtcLockScreen.apk
adb.exe shell rm /system/app/htcmailwidgets3d.apk
adb.exe shell rm /system/app/HTCMediaAutoUploadSetting.apk
adb.exe shell rm /system/app/HtcMediaCacheService.apk
adb.exe shell rm /system/app/HtcMIM.apk
adb.exe shell rm /system/app/HtcMimWidget.apk
adb.exe shell rm /system/app/HtcPhotoWidget.apk
adb.exe shell rm /system/app/HtcPowerSaverWidget.apk
adb.exe shell rm /system/app/HtcPowerStripWidget.apk
adb.exe shell rm /system/app/HtcProfileWidget.apk
adb.exe shell rm /system/app/HtcResetNotify.apk
adb.exe shell rm /system/app/HtcRingtoneTrimmer.apk
adb.exe shell rm /system/app/HtcRingtoneWidget.apk
adb.exe shell rm /system/app/HtcScreenBrightnessWidget.apk
adb.exe shell rm /system/app/HtcScreenTimeoutWidget.apk
adb.exe shell rm /system/app/htcsettingwidgets.apk
adb.exe shell rm /system/app/HTCSetupWizard.apk
adb.exe shell rm /system/app/HtcSoundRecorder.apk
adb.exe shell rm /system/app/HtcSSOClient.apk
adb.exe shell rm /system/app/HTCSync.apk
adb.exe shell rm /system/app/HtcTwitter.apk
adb.exe shell rm /system/app/HtcVideoPlayer.apk
adb.exe shell rm /system/app/htcwatchwidget3d.apk
adb.exe shell rm /system/app/HtcWeather3DWidget.apk
adb.exe shell rm /system/app/HtcWeatherWallpaper.apk
adb.exe shell rm /system/app/Idlescreen_Base.apk
adb.exe shell rm /system/app/idlescreen_photo.apk
adb.exe shell rm /system/app/idlescreen_shortcut.apk
adb.exe shell rm /system/app/IdleScreen_Stock.apk
adb.exe shell rm /system/app/IdleScreen_Weather.apk
adb.exe shell rm /system/app/Install_flash_player.apk
adb.exe shell rm /system/app/JETCET_PRINT.apk
adb.exe shell rm /system/app/JETCET_PRINT_Resources.apk
adb.exe shell rm /system/app/KeyChain.apk
adb.exe shell rm /system/app/Kindle.apk
adb.exe shell rm /system/app/LMW.apk
adb.exe shell rm /system/app/Mode10Wallpapers.apk
adb.exe shell rm /system/app/MyReportAgent.apk
adb.exe shell rm /system/app/MySketcher.apk
adb.exe shell rm /system/app/MyTask.apk
adb.exe shell rm /system/app/MyVerizon.apk
adb.exe shell rm /system/app/NewBayService-market.apk
adb.exe shell rm /system/app/NewBayService.apk
adb.exe shell rm /system/app/nfshp-signed-1.0.13.apk
adb.exe shell rm /system/app/NoiseField.apk
adb.exe shell rm /system/app/PhaseBeam.apk
adb.exe shell rm /system/app/picasapryramid.apk
adb.exe shell rm /system/app/PlusOne.apk
adb.exe shell rm /system/app/PolarisOffice.apk
adb.exe shell rm /system/app/PrivInit.apk
adb.exe shell rm /system/app/Protips.apk
adb.exe shell rm /system/app/qospermission.apk
adb.exe shell rm /system/app/RebootWarningWin.apk
adb.exe shell rm /system/app/Rosie.apk
adb.exe shell rm /system/app/SDCardWizard.apk
adb.exe shell rm /system/app/securesettingspermission.apk
adb.exe shell rm /system/app/SetupWizard.apk
adb.exe shell rm /system/app/slackerradio.apk
adb.exe shell rm /system/app/Stk.apk
adb.exe shell rm /system/app/Stock.apk
adb.exe shell rm /system/app/Street.apk
adb.exe shell rm /system/app/Talk.apk
adb.exe shell rm /system/app/Talk2.apk
adb.exe shell rm /system/app/talkback.apk
adb.exe shell rm /system/app/TetheringGuard.apk
adb.exe shell rm /system/app/TrimIt.apk
adb.exe shell rm /system/app/VerizonSSOEngine.apk
adb.exe shell rm /system/app/verizonWave.apk
adb.exe shell rm /system/app/VVM.apk
adb.exe shell rm /system/app/VzNav.apk
adb.exe shell rm /system/app/VzWBAClient.apk
adb.exe shell rm /system/app/VZWInstaller.apk
adb.exe shell rm /system/app/VzwLBSPerm.apk
adb.exe shell rm /system/app/WatchApp.apk
adb.exe shell rm /system/app/Weather.apk
adb.exe shell rm /system/app/WeatherLiveWallpaper.apk
adb.exe shell rm /system/app/WeatherProvider.apk
adb.exe shell rm /system/app/WeatherSyncProvider.apk
adb.exe shell rm /system/app/WeatherVideo.apk
adb.exe shell rm /system/app/WifiRouter.apk
adb.exe push stock_apks/Browser.apk /system/app/
adb.exe push stock_apks/Calculator.apk /system/app/
adb.exe push stock_apks/Calendar.apk /system/app/
adb.exe push stock_apks/CalendarProvider.apk /system/app/
adb.exe push stock_apks/DeskClock.apk /system/app/
adb.exe push stock_apks/Email.apk /system/app/
adb.exe push stock_apks/GoogleCalendarSyncAdapter.apk /system/app/
adb.exe push stock_apks/GoogleContactsSyncAdapter.apk /system/app/
adb.exe push stock_apks/LiveWallpapers.apk /system/app/
adb.exe push stock_apks/LiveWallpapersPicker.apk /system/app/
adb.exe reboot
